version: '3'

services:
  postgres_primary:
    container_name: postgres_primary
    image: postgres:14
    restart: always
    volumes:
      - ./db_data_example:/var/lib/postgresql/example_data
      - ./db_data_tpch:/var/lib/postgresql/tpch_data
      #
      - ./data:/var/lib/postgresql/data
      - ./data-secondary:/var/lib/postgresql/data-secondary
      - ./initialization:/etc/postgresql/initialization
      - ./migrations:/docker-entrypoint-initdb.d
      - ./entrypoints:/entrypoints
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 2

  postgres_secondary:
    container_name: postgres_secondary
    image: postgres:14
    restart: always
    volumes:
      - ./data-secondary:/var/lib/postgresql/data
      - ./initialization:/etc/postgresql/initialization
      - ./entrypoints:/entrypoints
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres_primary
